### ISSUE TITLE
Issue with dplyr and tidyverse for hw02

### ISSUE THREAD

**Issue by mksm1228** [STAT545-UBC-hw-2019-20/Announcements#11]
I'm not sure how to replicate this issue but when I load tidyverse, I get a message telling me there is a conflict:

x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

I can't use the filter function, filter (), properly in this situation. It's super weird because I had no problem using the filter function in cm006.....

**Comment by yuliaUU** [comment]
Please provide a reproducible example: a chunk of code that will tell us a dataset and what you are trying to do, so people can just copy-paste it into their R and run it. It will make it easier for us to help you and also speed up the whole process. 
- more instructions on how to create a reproducible example can be found [here](https://stackoverflow.com/help/minimal-reproducible-example) or [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

you can try the following: it should not happen if you load the package in the correct order you want. Restart your R session (this will detach all your current packages) and load the package in the order so that the last ones masked the first ones.

**Comment by dy-lin** [comment]
@mksm1228, what do you mean that you can't use the `filter()` function properly? Do you get an error?

**Comment by vincenzocoia** [comment]
I think the error messages:

```
x dplyr::filter() masks stats::filter()
x dplyr::lag() masks stats::lag()
```

are not related to the error you're getting. This just means that there are functions in the tidyverse called `filter()` and `lag()` that are going to be used in place of the base R functions `filter()` and `lag()`.

@mksm1228 I do encourage you to try making a reproducible example! It would be good practice. Don't worry if you don't get the reproducible example "just right", we'll try to help you through it.

**Comment by mksm1228** [comment]
Thanks for the clarification Vincenzo! I was confused as to why that appeared but my code and filter function works fine now.

Best,
Martin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
